import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--inter-font",
  subsets: ["latin"],
  weight: "700",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>NaNet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.variable}`}>
        <h1>
          Encontre os
          <span> recursos</span> necessários para seu
          <span> projeto</span>.
        </h1>
        <p>
          Uma coleção com links de recursos gratuitos para desenvolvimentos e
          estudos.
        </p>

        <section className={styles.web}>
          <div className={styles.header}>
            <span></span>
            <span></span>
            <span></span>
          </div>
          <div className={styles.body}>
            <div className={styles.content}>
              <div>
                <span></span>
                <span></span>
                <span></span>
              </div>
              <div>
                <span></span>
                <span></span>
              </div>
              <span></span>
              <span></span>
            </div>
            <div className={styles.images}>
              <div></div>
              <div></div>
              <div></div>
            </div>
          </div>

          <div className={styles.footer}>
            <span></span>
            <span></span>
          </div>
        </section>
      </main>
    </>
  );
}
